### ISSUE TITLE
plugin.xml defines all extension points with dynamic="true"

### ISSUE THREAD

**Issue by YannCebron** [stefansjs/flatbuffers-intellij-plugin#29]
this is not valid, this attribute must be specified on declaration of Extension Point only (https://plugins.jetbrains.com/docs/intellij/plugin-extension-points.html#dynamic-extension-points), not actual usages

**Comment by stefansjs** [comment]
Thanks @YannCebron for the bug report. I was attempting to follow the documentation here https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html#use-only-dynamic-extensions for enabling dynamic plugin loading. It says "... all extensions must be marked as dynamic". But according to the document you sent it's only _extension**Points**_. Is that correct?

(I'm just a bit lost on how to enable dynamic plugin loading.)

**Comment by YannCebron** [comment]
I see this sentence is indeed misleading, will fix. Your plugin cannot influence whether extension points are dynamic or not as the declaration is inside IntelliJ Platform, possibly version specific as well.
