### ISSUE TITLE
Fixed size arrays aren't supported

### ISSUE THREAD

**Issue by throwable-one** [stefansjs/flatbuffers-intellij-plugin#36]
i.e
```
struct Blob {
    data: [uint8:42];
}
```

**Comment by stefansjs** [comment]
Apologies. I've fixed this but not released it yet. I'll work on a release shortly. Fixed in https://github.com/stefansjs/flatbuffers-intellij-plugin/issues/31, https://github.com/stefansjs/flatbuffers-intellij-plugin/pull/32
