### ISSUE TITLE
Support for fixed size arrays

### ISSUE THREAD

**Issue by admo** [stefansjs/flatbuffers-intellij-plugin#38]
Hi,
Consider such schema
```
struct F
{
  f: [int:16];
}
```
which is fixed size [array](https://flatbuffers.dev/flatbuffers_guide_writing_schema.html#:~:text=Arrays) is allowed. However, the plugins highlight this part as an syntax error.

**Comment by stefansjs** [comment]
Thanks for the bug report. This is a duplicate of #31, which is going out with the latest release. JetBrains is currently processing the release, but it should be available to IDEs in the next few days.
