### ISSUE TITLE
Table fails when field names are reserved keywords

### ISSUE THREAD

**Issue by vaind** [stefansjs/flatbuffers-intellij-plugin#7]
First of all, thumbs up for the plugin.

I've just noticed the parser fails when a reserved keyword is used as a field name. This is perfectly valid flatbuffers schema:

```

table Typeful {
	id           : uint64	;
	int          : int		;
	int8         : int8		;
	int16        : int16	;
	int32        : int32	;
	int64        : int64	;
	uint         : uint		;
	uint8        : uint8	;
	uint16       : uint16	;
	uint32       : uint32	;
	uint64       : uint64	;
	bool         : bool		;
	string       : string	;
	stringvector : [string]	;
	byte         : byte		;
	ubyte        : ubyte	;
	bytevector   : [byte]	;
	ubytevector  : [ubyte]	;
	float32      : float32	;
	float64      : float64	;
	float        : float	;
	double       : double	;
}
```

**Comment by stefansjs** [comment]
Ouch, that will complicate the parser. Thanks for letting me know. I guess that's an undocumented feature. At least I don't see it documented explicitly https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html.

Thank you for the feedback! 👍

**Comment by stefansjs** [comment]
I'm working on a version increment that doesn't fix this bug but does tolerate parsing errors a bit better. I will work on including this bugfix in the next release after that, but I hope the plugin becomes more useful with better fault tolerance.
