### ISSUE TITLE
Support for Multiline Comments

### ISSUE THREAD

**Issue by Mythra** [stefansjs/flatbuffers-intellij-plugin#8]
Currently the parser errors when parsing multi-line comments inside of flatbuffer files e.g. something like:

```flatbuffer
namespace blah;

/**
 * Test
 *
 * Describes test in more detail
 */
table Test {
  /**
   * The ID of this connection.
   */
  a:string;
}
````

**Comment by stefansjs** [comment]
@SecurityInsanity thanks for the bug report. I pushed a fix this weekend and the latest version should be available https://plugins.jetbrains.com/plugin/14326-flatbuffers-support/update/88947. Let me know if you continue to have issues.
